
// the beat of the instrument for each seconds
// second represent the time of the music and size indicates how many times the instrument plays per second
let bass = [
  { second: 1, size: 2 },
  { second: 2, size: 1 },
  { second: 3, size: 2 },
  { second: 4, size: 1 },
  { second: 5, size: 1 },
  { second: 6, size: 2 },
  { second: 7, size: 1 },
  { second: 8, size: 2 },
  { second: 9, size: 2 },
  { second: 10, size: 1 },
  { second: 11, size: 1 },
  { second: 12, size: 1 },
  { second: 13, size: 3 },
  { second: 14, size: 1 },
  { second: 15, size: 2 },
  { second: 16, size: 0 },
  { second: 17, size: 2 },
  { second: 18, size: 3 },
  { second: 19, size: 3 },
  { second: 20, size: 5 },
  { second: 21, size: 3 },
  { second: 22, size: 1 },
  { second: 23, size: 2 },
  { second: 24, size: 1 },
  { second: 25, size: 1 },
  { second: 26, size: 0 },
  { second: 27, size: 0 },
  { second: 28, size: 0 },
  { second: 29, size: 3 },
  { second: 30, size: 1 }
];

let drums = [
  { second: 1, size: 2 },
  { second: 2, size: 2 },
  { second: 3, size: 2 },
  { second: 4, size: 1 },
  { second: 5, size: 8 },
  { second: 6, size: 4 },
  { second: 7, size: 4 },
  { second: 8, size: 6 },
  { second: 9, size: 6 },
  { second: 10, size: 4 },
  { second: 11, size: 4 },
  { second: 12, size: 2 },
  { second: 13, size: 7 },
  { second: 14, size: 4 },
  { second: 15, size: 5 },
  { second: 16, size: 2 },
  { second: 17, size: 2 },
  { second: 18, size: 2 },
  { second: 19, size: 2 },
  { second: 20, size: 2 },
  { second: 21, size: 2 },
  { second: 22, size: 2 },
  { second: 23, size: 2 },
  { second: 24, size: 2 },
  { second: 25, size: 2 },
  { second: 26, size: 2 },
  { second: 27, size: 8 },
  { second: 28, size: 2 },
  { second: 29, size: 3 },
  { second: 30, size: 4 }
];

let metronome = [
  { second: 1, size: 1 },
  { second: 2, size: 1 },
  { second: 3, size: 1},
  { second: 4, size: 1 },
  { second: 5, size: 1 },
  { second: 6, size: 1 },
  { second: 7, size: 1 },
  { second: 8, size: 1 },
  { second: 9, size: 1 },
  { second: 10, size: 1 },
  { second: 11, size: 1 },
  { second: 12, size: 1 },
  { second: 13, size: 1 },
  { second: 14, size: 1 },
  { second: 15, size: 1 },
  { second: 16, size: 1 },
  { second: 17, size: 1 },
  { second: 18, size: 1 },
  { second: 19, size: 1 },
  { second: 20, size: 1 },
  { second: 21, size: 1 },
  { second: 22, size: 1 },
  { second: 23, size: 1 },
  { second: 24, size: 1 },
  { second: 25, size: 1 },
  { second: 26, size: 1 },
  { second: 27, size: 1 },
  { second: 28, size: 1 },
  { second: 29, size: 1 },
  { second: 30, size: 1 }
];

let other = [
  { second: 1, size: 2 },
  { second: 2, size: 1 },
  { second: 3, size: 3 },
  { second: 4, size: 0 },
  { second: 5, size: 1 },
  { second: 6, size: 1 },
  { second: 7, size: 2 },
  { second: 8, size: 3 },
  { second: 9, size: 0 },
  { second: 10, size: 2 },
  { second: 11, size: 1 },
  { second: 12, size: 3 },
  { second: 13, size: 2 },
  { second: 14, size: 1 },
  { second: 15, size: 3 },
  { second: 16, size: 4 },
  { second: 17, size: 2 },
  { second: 18, size: 3 },
  { second: 19, size: 6 },
  { second: 20, size: 3 },
  { second: 21, size: 3 },
  { second: 22, size: 4 },
  { second: 23, size: 4 },
  { second: 24, size: 2 },
  { second: 25, size: 2 },
  { second: 26, size: 1 },
  { second: 27, size: 3 },
  { second: 28, size: 3 },
  { second: 29, size: 3 },
  { second: 30, size: 3 }
];
let vocals = [
  { second: 1, size: 0 },
  { second: 2, size: 0 },
  { second: 3, size: 0 },
  { second: 4, size: 0 },
  { second: 5, size: 2 },
  { second: 6, size: 2 },
  { second: 7, size: 1 },
  { second: 8, size: 0 },
  { second: 9, size: 2 },
  { second: 10, size: 2 },
  { second: 11, size: 3 },
  { second: 12, size: 2 },
  { second: 13, size: 2 },
  { second: 14, size: 1 },
  { second: 15, size: 0 },
  { second: 16, size: 3 },
  { second: 17, size: 0 },
  { second: 18, size: 0 },
  { second: 19, size: 2 },
  { second: 20, size: 0 },
  { second: 21, size: 0 },
  { second: 22, size: 0 },
  { second: 23, size: 1 },
  { second: 24, size: 0 },
  { second: 25, size: 0 },
  { second: 26, size: 5 },
  { second: 27, size: 0 },
  { second: 28, size: 0 },
  { second: 29, size: 0 },
  { second: 30, size: 0 }
];

